const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('petAPI', {
  moveWindow: (dx, dy) => ipcRenderer.send('move-window', { dx, dy }),
  setPosition: (x, y) => ipcRenderer.send('set-position', { x, y }),
  getBounds: () => ipcRenderer.invoke('get-bounds'),
  onAction: (callback) => ipcRenderer.on('action', (_, action) => callback(action)),
  getActivePet: () => ipcRenderer.invoke('get-active-pet'),
  onConfigChanged: (callback) => ipcRenderer.on('config-changed', (_, cfg) => callback(cfg)),
  quitApp: () => ipcRenderer.send('quit-app'),
  openSettings: () => ipcRenderer.send('open-settings'),
  setIgnoreMouseEvents: (ignore, opts) => ipcRenderer.send('set-ignore-mouse', ignore, opts),
  onInputEvent: (callback) => ipcRenderer.on('input-event', (_, type) => callback(type)),
  getScreenSize: () => ipcRenderer.invoke('get-screen-size'),
  getSystemInfo: () => ipcRenderer.invoke('get-system-info'),
  claudeChat: (msg) => ipcRenderer.invoke('claude-chat', msg),
  claudeClearHistory: () => ipcRenderer.send('claude-clear-history'),
  getActivityState: () => ipcRenderer.invoke('get-activity-state'),
  onActivityChanged: (cb) => ipcRenderer.on('activity-changed', (_, data) => cb(data)),
  getPomodoroState: () => ipcRenderer.invoke('get-pomodoro-state'),
  pomodoroStart: () => ipcRenderer.send('pomodoro-start'),
  pomodoroPause: () => ipcRenderer.send('pomodoro-pause'),
  pomodoroStop: () => ipcRenderer.send('pomodoro-stop'),
  pomodoroSkip: () => ipcRenderer.send('pomodoro-skip'),
  onPomodoroTick: (cb) => ipcRenderer.on('pomodoro-tick', (_, data) => cb(data)),
  getWeather: () => ipcRenderer.invoke('get-weather'),
  getNews: () => ipcRenderer.invoke('get-news'),
  onClipboardChanged: (cb) => ipcRenderer.on('clipboard-changed', (_, data) => cb(data)),
  onSedentaryReminder: (cb) => ipcRenderer.on('sedentary-reminder', () => cb()),
  onUpdateStatus: (cb) => ipcRenderer.on('update-status', (_, status, version) => cb(status, version)),
  getGrowth: () => ipcRenderer.invoke('get-growth'),
  onLevelUp: (cb) => ipcRenderer.on('level-up', (_, data) => cb(data)),
  addCompanion: (breedId) => ipcRenderer.invoke('add-companion', breedId),
  removeCompanion: (breedId) => ipcRenderer.send('remove-companion', breedId),
  getCompanions: () => ipcRenderer.invoke('get-companions'),
  saveRecording: (base64, filename) => ipcRenderer.invoke('save-recording', base64, filename),
  transcribeAudio: (filePath) => ipcRenderer.invoke('transcribe-audio', filePath),
});
